name: Code Coverage

on:
  push:
    branches: [ master, unstable ]
  pull_request:
    branches: [ master, unstable ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
